[package]
name = "jvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
bitflags = "1.3"
paste = "1.0.6"
anyhow = "1.0.56"
thiserror = "1.0.30"